# Generated by Django 3.1.3 on 2022-11-13 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='メールアドレス')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='ユーザー名')),
                ('password', models.CharField(max_length=100, verbose_name='パスワード')),
                ('introduction', models.TextField(verbose_name='自己紹介文')),
                ('profile_image', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='投稿内容')),
                ('post_image', models.ImageField(upload_to='images')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日')),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pic_share_api.users')),
            ],
        ),
        migrations.CreateModel(
            name='Follow_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='pic_share_api.users')),
                ('followered_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followered', to='pic_share_api.users')),
            ],
        ),
    ]
