# Generated by Django 3.1.3 on 2022-10-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_id', models.IntegerField(verbose_name='ユーザーID')),
                ('content', models.TextField(verbose_name='投稿内容')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('delete_date', models.DateTimeField(verbose_name='削除日')),
            ],
        ),
    ]
