# Generated by Django 3.1.3 on 2022-10-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic_share_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='delete_date',
            field=models.DateTimeField(blank=True, verbose_name='削除日'),
        ),
    ]
