# Generated by Django 3.1.3 on 2022-11-02 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pic_share_api', '0003_auto_20221026_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='create_date',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='delete_date',
            new_name='delete_at',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='update_date',
            new_name='update_at',
        ),
    ]
