# Generated by Django 3.1.3 on 2022-11-12 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pic_share_api', '0004_auto_20221103_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_users', models.IntegerField(verbose_name='フォロー元ユーザー')),
                ('followered_users', models.IntegerField(verbose_name='フォロー先ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='メールアドレス')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='ユーザー名')),
                ('password', models.CharField(max_length=100, verbose_name='パスワード')),
                ('introduction', models.TextField(verbose_name='自己紹介文')),
                ('profile_image', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日')),
            ],
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='delete_at',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='posts',
            name='post_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images'),
            preserve_default=False,
        ),
    ]
